name: AntiSeedCracker
version: '${version}'
main: me.gadse.antiseedcracker.AntiSeedCracker
api-version: 1.20
folia-supported: true
authors: [Gadse]
description: Modifies the hashed seed sent to clients upon joining to make cracking the seed of your world harder

commands:
  antiseedcracker:
    permission: "antiseedcracker.admin"
    usage: /antiseedcracker [reload]
    description: Version info and config reload command of AntiSeedCracker
    aliases:
      - asc

permissions:
  antiseedcracker.admin:
    default: op
